/*
 * Created on 2023-06-08 ( 15:10:57 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package duan.sportify.entities;

import java.io.Serializable;
import jakarta.persistence.*;

/**
 * JPA entity class for "Authorized"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="authorized", catalog="sportify" )
public class Authorized implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="authorizedID", nullable=false)
    private Integer    authorizedid ;

    //--- ENTITY DATA FIELDS 
    @Column(name="username", nullable=false, length=16)
    private String     username ;

    @Column(name="roleId", nullable=false, length=10)
    private String     roleid ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="roleId", referencedColumnName="roleId", insertable=false, updatable=false)
    private Roles      roles ; 

    @ManyToOne
    @JoinColumn(name="username", referencedColumnName="username", insertable=false, updatable=false)
    private Users      users ; 


    /**
     * Constructor
     */
    public Authorized() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setAuthorizedid( Integer authorizedid ) {
        this.authorizedid = authorizedid ;
    }
    public Integer getAuthorizedid() {
        return this.authorizedid;
    }

    public void setUsername( String username ) {
        this.username = username ;
    }
    public String getUsername() {
        return this.username;
    }

    public void setRoleid( String roleid ) {
        this.roleid = roleid ;
    }
    public String getRoleid() {
        return this.roleid;
    }

    //--- GETTERS FOR LINKS
    public Roles getRoles() {
        return this.roles;
    } 

    public Users getUsers() {
        return this.users;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(authorizedid);
        sb.append("|");
        sb.append(username);
        sb.append("|");
        sb.append(roleid);
        return sb.toString(); 
    } 

}
