/*
 * Created on 2023-06-06 ( 15:20:49 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package duan.sportify.entities;

import java.io.Serializable;
import jakarta.persistence.*;

/**
 * JPA entity class for "Bookingdetails"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="bookingdetails", catalog="sportify" )
public class Bookingdetails implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="bookingdetailID", nullable=false)
    private Integer    bookingdetailid ;

    //--- ENTITY DATA FIELDS 
    @Column(name="bookingID", nullable=false)
    private Integer    bookingid ;

    @Column(name="shiftID", nullable=false)
    private Integer    shiftid ;

    @Column(name="fieldID", nullable=false)
    private Integer    fieldid ;

    @Column(name="price")
    private Double     price ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="shiftID", referencedColumnName="shiftID", insertable=false, updatable=false)
    private Shifts     shifts ; 

    @ManyToOne
    @JoinColumn(name="fieldID", referencedColumnName="fieldID", insertable=false, updatable=false)
    private Fields     fields ; 

    @ManyToOne
    @JoinColumn(name="bookingID", referencedColumnName="bookingID", insertable=false, updatable=false)
    private Bookings   bookings ; 


    /**
     * Constructor
     */
    public Bookingdetails() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setBookingdetailid( Integer bookingdetailid ) {
        this.bookingdetailid = bookingdetailid ;
    }
    public Integer getBookingdetailid() {
        return this.bookingdetailid;
    }

    public void setBookingid( Integer bookingid ) {
        this.bookingid = bookingid ;
    }
    public Integer getBookingid() {
        return this.bookingid;
    }

    public void setShiftid( Integer shiftid ) {
        this.shiftid = shiftid ;
    }
    public Integer getShiftid() {
        return this.shiftid;
    }

    public void setFieldid( Integer fieldid ) {
        this.fieldid = fieldid ;
    }
    public Integer getFieldid() {
        return this.fieldid;
    }

    public void setPrice( Double price ) {
        this.price = price ;
    }
    public Double getPrice() {
        return this.price;
    }

    //--- GETTERS FOR LINKS
    public Shifts getShifts() {
        return this.shifts;
    } 

    public Fields getFields() {
        return this.fields;
    } 

    public Bookings getBookings() {
        return this.bookings;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(bookingdetailid);
        sb.append("|");
        sb.append(bookingid);
        sb.append("|");
        sb.append(shiftid);
        sb.append("|");
        sb.append(fieldid);
        sb.append("|");
        sb.append(price);
        return sb.toString(); 
    } 

}
