/*
 * Created on 2023-05-31 ( 14:37:07 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package duan.sportify.entities;

import java.io.Serializable;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;


/**
 * JPA entity class for "Bookingdetails"
 *
 * @author Telosys
 *
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name="bookingdetails", catalog="sportify" )
public class Bookingdetails implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="bookingdetailID", nullable=false)
    private Integer    bookingdetailid ;

    //--- ENTITY DATA FIELDS 
    @Column(name="bookingID", nullable=false)
    private Integer    bookingid ;

    @Column(name="shiftID", nullable=false)
    private Integer    shiftid ;

    @Column(name="fieldID", nullable=false)
    private Integer    fieldid ;

    @Column(name="price")
    private Double     price ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="shiftID", referencedColumnName="shiftID", insertable=false, updatable=false)
    private Shifts     shifts ; 

    @ManyToOne
    @JoinColumn(name="fieldID", referencedColumnName="fieldID", insertable=false, updatable=false)
    private Fields     fields ; 

    @ManyToOne
    @JoinColumn(name="bookingID", referencedColumnName="bookingID", insertable=false, updatable=false)
    private Bookings   bookings ; 


    

}
