/*
 * Created on 2023-06-14 ( 09:06:03 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package duan.sportify.entities;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * JPA entity class for "Bookingdetails"
 *
 * @author Telosys
 *
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name="bookingdetails", catalog="sportify" )
public class Bookingdetails implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="bookingdetailid", nullable=false)
    private Integer    bookingdetailid ;

    //--- ENTITY DATA FIELDS 
    @Column(name="bookingid", nullable=false)
    private Integer    bookingid ;

    @Column(name="shiftid", nullable=false)
    private Integer    shiftid ;
    
    @Temporal(TemporalType.DATE)
    @Column(name="playdate", nullable=false)
    private Date       playdate ;

    @Column(name="fieldid", nullable=false)
    private Integer    fieldid ;

    @Column(name="price")
    private Double     price ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="fieldid", referencedColumnName="fieldid", insertable=false, updatable=false)
    private Field      field ; 

    @ManyToOne
    @JoinColumn(name="bookingid", referencedColumnName="bookingid", insertable=false, updatable=false)
    private Bookings   bookings ; 

    @ManyToOne
    @JoinColumn(name="shiftid", referencedColumnName="shiftid", insertable=false, updatable=false)
    private Shifts     shifts ; 


    

}
