/*
 * Created on 2023-06-08 ( 15:10:58 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package duan.sportify.entities;

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import jakarta.persistence.*;

/**
 * JPA entity class for "Bookings"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="bookings", catalog="sportify" )
public class Bookings implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="bookingID", nullable=false)
    private Integer    bookingid ;

    //--- ENTITY DATA FIELDS 
    @Column(name="username", nullable=false, length=16)
    private String     username ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="bookingDate", nullable=false)
    private Date       bookingdate ;

    @Column(name="bookingPrice", nullable=false)
    private Double     bookingprice ;

    @Column(name="phone", nullable=false, length=10)
    private String     phone ;

    @Column(name="note", length=200)
    private String     note ;

    @Column(name="bookingStatus", nullable=false, length=16)
    private String     bookingstatus ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="bookings")
    private List<Bookingdetails> listOfBookingdetails ; 

    @ManyToOne
    @JoinColumn(name="username", referencedColumnName="username", insertable=false, updatable=false)
    private Users      users ; 


    /**
     * Constructor
     */
    public Bookings() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setBookingid( Integer bookingid ) {
        this.bookingid = bookingid ;
    }
    public Integer getBookingid() {
        return this.bookingid;
    }

    public void setUsername( String username ) {
        this.username = username ;
    }
    public String getUsername() {
        return this.username;
    }

    public void setBookingdate( Date bookingdate ) {
        this.bookingdate = bookingdate ;
    }
    public Date getBookingdate() {
        return this.bookingdate;
    }

    public void setBookingprice( Double bookingprice ) {
        this.bookingprice = bookingprice ;
    }
    public Double getBookingprice() {
        return this.bookingprice;
    }

    public void setPhone( String phone ) {
        this.phone = phone ;
    }
    public String getPhone() {
        return this.phone;
    }

    public void setNote( String note ) {
        this.note = note ;
    }
    public String getNote() {
        return this.note;
    }

    public void setBookingstatus( String bookingstatus ) {
        this.bookingstatus = bookingstatus ;
    }
    public String getBookingstatus() {
        return this.bookingstatus;
    }

    //--- GETTERS FOR LINKS
    public List<Bookingdetails> getListOfBookingdetails() {
        return this.listOfBookingdetails;
    } 

    public Users getUsers() {
        return this.users;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(bookingid);
        sb.append("|");
        sb.append(username);
        sb.append("|");
        sb.append(bookingdate);
        sb.append("|");
        sb.append(bookingprice);
        sb.append("|");
        sb.append(phone);
        sb.append("|");
        sb.append(note);
        sb.append("|");
        sb.append(bookingstatus);
        return sb.toString(); 
    } 

}
