/*
 * Created on 2023-05-31 ( 14:37:07 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package duan.sportify.entities;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;


/**
 * JPA entity class for "Bookings"
 *
 * @author Telosys
 *
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name="bookings", catalog="sportify" )
public class Bookings implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="bookingID", nullable=false)
    private Integer    bookingid ;

    //--- ENTITY DATA FIELDS 
    @Column(name="username", nullable=false, length=16)
    private String     username ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="bookingDate", nullable=false)
    private Date       bookingdate ;

    @Column(name="bookingPrice", nullable=false)
    private Double     bookingprice ;

    @Column(name="phone", nullable=false, length=10)
    private String     phone ;

    @Column(name="note", length=200)
    private String     note ;

    @Column(name="bookingStatus", nullable=false, length=12)
    private String     bookingstatus ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="bookings")
    private List<Bookingdetails> listOfBookingdetails ; 

    @OneToMany(mappedBy="bookings")
    private List<Cancelbooking> listOfCancelbooking ; 

    @ManyToOne
    @JoinColumn(name="username", referencedColumnName="username", insertable=false, updatable=false)
    private Users      users ; 


    

}
