/*
 * Created on 2023-05-31 ( 14:37:07 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package duan.sportify.entities;

import java.io.Serializable;
import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;


/**
 * JPA entity class for "Cancelbooking"
 *
 * @author Telosys
 *
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name="cancelbooking", catalog="sportify" )
public class Cancelbooking implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="cancelBookingID", nullable=false)
    private Integer    cancelbookingid ;

    //--- ENTITY DATA FIELDS 
    @Column(name="username", nullable=false, length=16)
    private String     username ;

    @Column(name="bookingID", nullable=false)
    private Integer    bookingid ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="timeCancel", nullable=false)
    private Date       timecancel ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="username", referencedColumnName="username", insertable=false, updatable=false)
    private Users      users ; 

    @ManyToOne
    @JoinColumn(name="bookingID", referencedColumnName="bookingID", insertable=false, updatable=false)
    private Bookings   bookings ; 


    

}
