/*
 * Created on 2023-05-31 ( 14:37:07 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package duan.sportify.entities;

import java.io.Serializable;
import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;


/**
 * JPA entity class for "Events"
 *
 * @author Telosys
 *
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name="events", catalog="sportify" )
public class Events implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="eventID", nullable=false)
    private Integer    eventid ;

    //--- ENTITY DATA FIELDS 
    @Column(name="nameEvent", nullable=false, length=50)
    private String     nameevent ;

    @Column(name="typeEvent", nullable=false, length=50)
    private String     typeevent ;

    @Temporal(TemporalType.DATE)
    @Column(name="dateStart", nullable=false)
    private Date       datestart ;

    @Temporal(TemporalType.DATE)
    @Column(name="dateEnd", nullable=false)
    private Date       dateend ;

    @Column(name="image", length=50)
    private String     image ;

    @Column(name="descriptions", length=255)
    private String     descriptions ;


    

}
