/*
 * Created on 2023-06-08 ( 15:10:58 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package duan.sportify.entities;

import java.io.Serializable;
import java.util.Date;
import jakarta.persistence.*;

/**
 * JPA entity class for "Events"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="events", catalog="sportify" )
public class Events implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="eventID", nullable=false)
    private Integer    eventid ;

    //--- ENTITY DATA FIELDS 
    @Column(name="nameEvent", nullable=false, length=50)
    private String     nameevent ;

    @Temporal(TemporalType.DATE)
    @Column(name="dateStart", nullable=false)
    private Date       datestart ;

    @Temporal(TemporalType.DATE)
    @Column(name="dateEnd", nullable=false)
    private Date       dateend ;

    @Column(name="image", length=100)
    private String     image ;

    @Column(name="descriptions", length=1000)
    private String     descriptions ;


    //--- ENTITY LINKS ( RELATIONSHIP )

    /**
     * Constructor
     */
    public Events() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setEventid( Integer eventid ) {
        this.eventid = eventid ;
    }
    public Integer getEventid() {
        return this.eventid;
    }

    public void setNameevent( String nameevent ) {
        this.nameevent = nameevent ;
    }
    public String getNameevent() {
        return this.nameevent;
    }

    public void setDatestart( Date datestart ) {
        this.datestart = datestart ;
    }
    public Date getDatestart() {
        return this.datestart;
    }

    public void setDateend( Date dateend ) {
        this.dateend = dateend ;
    }
    public Date getDateend() {
        return this.dateend;
    }

    public void setImage( String image ) {
        this.image = image ;
    }
    public String getImage() {
        return this.image;
    }

    public void setDescriptions( String descriptions ) {
        this.descriptions = descriptions ;
    }
    public String getDescriptions() {
        return this.descriptions;
    }

    //--- GETTERS FOR LINKS
    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(eventid);
        sb.append("|");
        sb.append(nameevent);
        sb.append("|");
        sb.append(datestart);
        sb.append("|");
        sb.append(dateend);
        sb.append("|");
        sb.append(image);
        sb.append("|");
        sb.append(descriptions);
        return sb.toString(); 
    } 

}
