/*
 * Created on 2023-06-14 ( 09:06:03 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package duan.sportify.entities;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * JPA entity class for "Favoritefield"
 *
 * @author Telosys
 *
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name="favoritefield", catalog="sportify" )
public class Favoritefield implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="favoriteid", nullable=false)
    private Integer    favoriteid ;

    //--- ENTITY DATA FIELDS 
    @Column(name="fieldid", nullable=false)
    private Integer    fieldid ;

    @Column(name="username", nullable=false, length=16)
    private String     username ;

    @Column(name="statusfavorite", nullable=false)
    private Boolean    statusfavorite ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="username", referencedColumnName="username", insertable=false, updatable=false)
    private Users      users ; 

    @ManyToOne
    @JoinColumn(name="fieldid", referencedColumnName="fieldid", insertable=false, updatable=false)
    private Field      field ; 


   
}
