/*
 * Created on 2023-05-31 ( 14:37:07 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package duan.sportify.entities;

import java.io.Serializable;
import java.util.List;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;


/**
 * JPA entity class for "Fields"
 *
 * @author Telosys
 *
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name="fields", catalog="sportify" )
public class Fields implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="fieldID", nullable=false)
    private Integer    fieldid ;

    //--- ENTITY DATA FIELDS 
    @Column(name="sportTypeID", nullable=false, length=6)
    private String     sporttypeid ;

    @Column(name="nameField", nullable=false, length=50)
    private String     namefield ;

    @Column(name="descriptionField", length=200)
    private String     descriptionfield ;

    @Column(name="price", nullable=false)
    private Double     price ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="sportTypeID", referencedColumnName="sportTypeID", insertable=false, updatable=false)
    private Sporttype  sporttype ; 

    @OneToMany(mappedBy="fields")
    private List<Favoritefield> listOfFavoritefield ; 

    @OneToMany(mappedBy="fields")
    private List<Bookingdetails> listOfBookingdetails ; 


     

}
