/*
 * Created on 2023-05-31 ( 14:37:07 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package duan.sportify.entities;

import java.io.Serializable;
import java.util.Date;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * JPA entity class for "Mgrproducts"
 *
 * @author Telosys
 *
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name="mgrproducts", catalog="sportify" )
public class Mgrproducts implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="mgrProductID", nullable=false)
    private Integer    mgrproductid ;

    //--- ENTITY DATA FIELDS 
    @Column(name="productID", nullable=false)
    private Integer    productid ;

    @Column(name="sizeID", nullable=false)
    private Integer    sizeid ;

    @Column(name="quantity", nullable=false)
    private Integer    quantity ;

    @Temporal(TemporalType.DATE)
    @Column(name="importDate", nullable=false)
    private Date       importdate ;

    @Column(name="price", nullable=false)
    private Double     price ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="sizeID", referencedColumnName="sizeID", insertable=false, updatable=false)
    private Sizes      sizes ; 

    @ManyToOne
    @JoinColumn(name="productID", referencedColumnName="productID", insertable=false, updatable=false)
    private Products   products ; 


    

}
