/*
 * Created on 2023-06-14 ( 09:06:03 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package duan.sportify.entities;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * JPA entity class for "Orders"
 *
 * @author Telosys
 *
 */
@Data
//@JsonIgnoreProperties(ignoreUnknown = true)
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name = "orders", catalog = "sportify")
public class Orders implements Serializable {

	private static final long serialVersionUID = 1L;

//	@Id
//	@GeneratedValue(strategy = GenerationType.IDENTITY)
//	Integer orderid;
//
//	String username;
//
//	@Temporal(TemporalType.TIMESTAMP)
//	Date createdate;
//	
//	String address;
//	String note;
//	String orderstatus;
//	Boolean paymentstatus;
//	
//	@ManyToOne
//	@JoinColumn(name = "username", referencedColumnName = "username", insertable = false, updatable = false)
//	Users users;
//	
//	@JsonIgnore
//	@OneToMany(mappedBy = "orders")
//	List<Orderdetails> orderDetails;
	
    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="orderid", nullable=false)
    private Integer    orderid ;

    //--- ENTITY DATA FIELDS 
    @Column(name="username", nullable=false, length=16)
    private String     username ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createdate", nullable=false)
    private Date       createdate ;

    @Column(name="address", nullable=false, length=100)
    private String     address ;

    @Column(name="note", length=1000)
    private String     note ;

    @Column(name="orderstatus", nullable=false, length=12)
    private String     orderstatus ;
    @Column(name="paymentstatus", nullable=false)
    private Boolean     paymentstatus ;
    @Column(name="totalprice", nullable=false)
    private Double     totalprice ;

    //--- ENTITY LINKS ( RELATIONSHIP )
   
    @ManyToOne
    @JoinColumn(name="username", referencedColumnName="username", insertable=false, updatable=false)
    private Users      users ;
    
    @JsonIgnore
    @OneToMany(mappedBy="orders")
    private List<Orderdetails> orderDetails ; 

}
