/*
 * Created on 2023-06-14 ( 09:06:03 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package duan.sportify.entities;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * JPA entity class for "Orderdetails"
 *
 * @author Telosys
 *
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name = "orderdetails", catalog = "sportify")
public class Orderdetails implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	Integer orderdetailsid;
	Double price;
	Integer quantity;

	@ManyToOne
	@JoinColumn(name = "productid")
	Products products;
	@ManyToOne
	@JoinColumn(name = "orderid")
	Orders orders;
	
//    //--- ENTITY PRIMARY KEY 
//    @Id
//    @GeneratedValue(strategy=GenerationType.IDENTITY)
//    @Column(name="orderdetailsid", nullable=false)
//    private Integer    orderdetailsid ;
//
//    //--- ENTITY DATA FIELDS 
//    @Column(name="orderid", nullable=false)
//    private Integer    orderid ;
//
//    @Column(name="productid", nullable=false)
//    private Integer    productid ;
//
//    @Column(name="price", nullable=false)
//    private Double     price ;
//
//    @Column(name="quantity", nullable=false)
//    private Integer    quantity ;
//
//    //--- ENTITY LINKS ( RELATIONSHIP )
//    
//    @ManyToOne
//    @JoinColumn(name="orderid", referencedColumnName="orderid", insertable=false, updatable=false)
//     Orders     orders ; 
//    @ManyToOne
//    @JoinColumn(name="productid", referencedColumnName="productid", insertable=false, updatable=false)
//     Products   products ; 

}
