/*
 * Created on 2023-06-06 ( 15:20:49 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package duan.sportify.entities;

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import jakarta.persistence.*;

/**
 * JPA entity class for "Orders"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="orders", catalog="sportify" )
public class Orders implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="orderID", nullable=false)
    private Integer    orderid ;

    //--- ENTITY DATA FIELDS 
    @Column(name="username", nullable=false, length=16)
    private String     username ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createDate", nullable=false)
    private Date       createdate ;

    @Column(name="address", nullable=false, length=100)
    private String     address ;

    @Column(name="note", length=1000)
    private String     note ;

    @Column(name="orderStatus", nullable=false, length=12)
    private String     orderstatus ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="orders")
    private List<Orderdetails> listOfOrderdetails ; 

    @ManyToOne
    @JoinColumn(name="username", referencedColumnName="username", insertable=false, updatable=false)
    private Users      users ; 


    /**
     * Constructor
     */
    public Orders() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setOrderid( Integer orderid ) {
        this.orderid = orderid ;
    }
    public Integer getOrderid() {
        return this.orderid;
    }

    public void setUsername( String username ) {
        this.username = username ;
    }
    public String getUsername() {
        return this.username;
    }

    public void setCreatedate( Date createdate ) {
        this.createdate = createdate ;
    }
    public Date getCreatedate() {
        return this.createdate;
    }

    public void setAddress( String address ) {
        this.address = address ;
    }
    public String getAddress() {
        return this.address;
    }

    public void setNote( String note ) {
        this.note = note ;
    }
    public String getNote() {
        return this.note;
    }

    public void setOrderstatus( String orderstatus ) {
        this.orderstatus = orderstatus ;
    }
    public String getOrderstatus() {
        return this.orderstatus;
    }

    //--- GETTERS FOR LINKS
    public List<Orderdetails> getListOfOrderdetails() {
        return this.listOfOrderdetails;
    } 

    public Users getUsers() {
        return this.users;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(orderid);
        sb.append("|");
        sb.append(username);
        sb.append("|");
        sb.append(createdate);
        sb.append("|");
        sb.append(address);
        sb.append("|");
        sb.append(note);
        sb.append("|");
        sb.append(orderstatus);
        return sb.toString(); 
    } 

}
