/*
 * Created on 2023-05-31 ( 14:37:07 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package duan.sportify.entities;

import java.io.Serializable;


import jakarta.persistence.*;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * JPA entity class for "Orderdetails"
 *
 * @author Telosys
 *
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name="orderdetails", catalog="sportify" )
public class Orderdetails implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="orderDetailsID", nullable=false)
    private Integer    orderdetailsid ;

    //--- ENTITY DATA FIELDS 
    @Column(name="orderID", nullable=false)
    private Integer    orderid ;

    @Column(name="productID", nullable=false)
    private Integer    productid ;

    @Column(name="price", nullable=false)
    private Double     price ;

    @Column(name="quantity", nullable=false)
    private Integer    quantity ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="orderID", referencedColumnName="orderID", insertable=false, updatable=false)
    private Orders     orders ; 

    @ManyToOne
    @JoinColumn(name="productID", referencedColumnName="productID", insertable=false, updatable=false)
    private Products   products ; 


    

}
