/*
 * Created on 2023-06-06 ( 15:20:49 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package duan.sportify.entities;

import java.io.Serializable;
import jakarta.persistence.*;

/**
 * JPA entity class for "Orderdetails"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="orderdetails", catalog="sportify" )
public class Orderdetails implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="orderDetailsID", nullable=false)
    private Integer    orderdetailsid ;

    //--- ENTITY DATA FIELDS 
    @Column(name="orderID", nullable=false)
    private Integer    orderid ;

    @Column(name="productID", nullable=false)
    private Integer    productid ;

    @Column(name="price", nullable=false)
    private Double     price ;

    @Column(name="quantity", nullable=false)
    private Integer    quantity ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="orderID", referencedColumnName="orderID", insertable=false, updatable=false)
    private Orders     orders ; 

    @ManyToOne
    @JoinColumn(name="productID", referencedColumnName="productID", insertable=false, updatable=false)
    private Products   products ; 


    /**
     * Constructor
     */
    public Orderdetails() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setOrderdetailsid( Integer orderdetailsid ) {
        this.orderdetailsid = orderdetailsid ;
    }
    public Integer getOrderdetailsid() {
        return this.orderdetailsid;
    }

    public void setOrderid( Integer orderid ) {
        this.orderid = orderid ;
    }
    public Integer getOrderid() {
        return this.orderid;
    }

    public void setProductid( Integer productid ) {
        this.productid = productid ;
    }
    public Integer getProductid() {
        return this.productid;
    }

    public void setPrice( Double price ) {
        this.price = price ;
    }
    public Double getPrice() {
        return this.price;
    }

    public void setQuantity( Integer quantity ) {
        this.quantity = quantity ;
    }
    public Integer getQuantity() {
        return this.quantity;
    }

    //--- GETTERS FOR LINKS
    public Orders getOrders() {
        return this.orders;
    } 

    public Products getProducts() {
        return this.products;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(orderdetailsid);
        sb.append("|");
        sb.append(orderid);
        sb.append("|");
        sb.append(productid);
        sb.append("|");
        sb.append(price);
        sb.append("|");
        sb.append(quantity);
        return sb.toString(); 
    } 

}
