/*
 * Created on 2023-05-31 ( 14:37:07 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package duan.sportify.entities;

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * JPA entity class for "Products"
 *
 * @author Telosys
 *
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name="products", catalog="sportify" )
public class Products implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="productID", nullable=false)
    private Integer    productid ;

    //--- ENTITY DATA FIELDS 
    @Column(name="categoryID", nullable=false)
    private Integer    categoryid ;

    @Column(name="productName", nullable=false, length=50)
    private String     productname ;

    @Column(name="image", length=50)
    private String     image ;

    @Column(name="discountPrice")
    private Double     discountprice ;

    @Temporal(TemporalType.DATE)
    @Column(name="dateCreate", nullable=false)
    private Date       datecreate ;

    @Column(name="price", nullable=false)
    private Double     price ;

    @Column(name="productStatus", nullable=false)
    private Boolean    productstatus ;

    @Column(name="descriptions", length=200)
    private String     descriptions ;

    @Column(name="quantity", nullable=false)
    private Integer    quantity ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="products")
    private List<Orderdetails> listOfOrderdetails ; 

    @ManyToOne
    @JoinColumn(name="categoryID", referencedColumnName="categoryID", insertable=false, updatable=false)
    private Categories categories ; 

    @OneToMany(mappedBy="products")
    private List<Mgrproducts> listOfMgrproducts ; 


    

}
