/*
 * Created on 2023-06-14 ( 09:06:03 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package duan.sportify.entities;

import java.io.Serializable;
import java.time.LocalDate;
import java.util.Date;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnore;

import jakarta.persistence.*;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * JPA entity class for "Products"
 *
 * @author Telosys
 *
 */
@SuppressWarnings("unused")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name="products", catalog="sportify" )
public class Products implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="productid", nullable=false)
    private Integer    productid ;

    //--- ENTITY DATA FIELDS 
    @Column(name="categoryid", nullable=false)
    private Integer    categoryid ;

    @Column(name="productname", nullable=false, length=50)
    private String     productname ;

    @Column(name="image", length=50)
    private String     image ;

    @Column(name="discountprice")
    private Double     discountprice ;

    @Temporal(TemporalType.DATE)
    @Column(name="datecreate", nullable=false)
    private LocalDate       datecreate ;

    @Column(name="price", nullable=false)
    private Double     price ;

    @Column(name="productstatus", nullable=false)
    private Boolean    productstatus ;

    @Column(name="descriptions", length=200)
    private String     descriptions ;

    @Column(name="quantity", nullable=false)
    private Integer    quantity ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="categoryid", referencedColumnName="categoryid", insertable=false, updatable=false)
    private Categories categories ; 
    @JsonIgnore
    @OneToMany(mappedBy="products")
    private List<Orderdetails> listOfOrderdetails ; 


    

}
