/*
 * Created on 2023-06-08 ( 15:10:58 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package duan.sportify.entities;

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import jakarta.persistence.*;

/**
 * JPA entity class for "Shifts"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="shifts", catalog="sportify" )
public class Shifts implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="shiftID", nullable=false)
    private Integer    shiftid ;

    //--- ENTITY DATA FIELDS 
    @Column(name="nameShift", nullable=false, length=100)
    private String     nameshift ;

    @Temporal(TemporalType.TIME)
    @Column(name="startTime", nullable=false)
    private Date       starttime ;

    @Temporal(TemporalType.TIME)
    @Column(name="endTime", nullable=false)
    private Date       endtime ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="shifts")
    private List<Bookingdetails> listOfBookingdetails ; 


    /**
     * Constructor
     */
    public Shifts() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setShiftid( Integer shiftid ) {
        this.shiftid = shiftid ;
    }
    public Integer getShiftid() {
        return this.shiftid;
    }

    public void setNameshift( String nameshift ) {
        this.nameshift = nameshift ;
    }
    public String getNameshift() {
        return this.nameshift;
    }

    public void setStarttime( Date starttime ) {
        this.starttime = starttime ;
    }
    public Date getStarttime() {
        return this.starttime;
    }

    public void setEndtime( Date endtime ) {
        this.endtime = endtime ;
    }
    public Date getEndtime() {
        return this.endtime;
    }

    //--- GETTERS FOR LINKS
    public List<Bookingdetails> getListOfBookingdetails() {
        return this.listOfBookingdetails;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(shiftid);
        sb.append("|");
        sb.append(nameshift);
        sb.append("|");
        sb.append(starttime);
        sb.append("|");
        sb.append(endtime);
        return sb.toString(); 
    } 

}
