/*
 * Created on 2023-06-14 ( 09:06:03 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package duan.sportify.entities;

import java.io.Serializable;
import java.time.LocalTime;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;


import com.fasterxml.jackson.annotation.JsonIgnore;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;








@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name="shifts", catalog="sportify" )
public class Shifts implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="shiftid", nullable=false)
    private Integer    shiftid ;

    //--- ENTITY DATA FIELDS 
    @Column(name="nameshift", nullable=false, length=100)
    private String     nameshift ;

    
    @Column(name="starttime", nullable=false)
    private LocalTime       starttime ;


    @Column(name="endtime", nullable=false)
    private LocalTime       endtime ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @JsonIgnore
    @OneToMany(mappedBy="shifts")
    private List<Bookingdetails> listOfBookingdetails ; 


   

}
