/*
 * Created on 2023-06-14 ( 09:06:03 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package duan.sportify.entities;

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import jakarta.persistence.*;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * JPA entity class for "Shifts"
 *
 * @author Telosys
 *
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name="shifts", catalog="sportify" )
public class Shifts implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="shiftid", nullable=false)
    private Integer    shiftid ;

    //--- ENTITY DATA FIELDS 
    @Column(name="nameshift", nullable=false, length=100)
    private String     nameshift ;

    @Temporal(TemporalType.TIME)
    @Column(name="starttime", nullable=false)
    private Date       starttime ;

    @Temporal(TemporalType.TIME)
    @Column(name="endtime", nullable=false)
    private Date       endtime ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="shifts")
    private List<Bookingdetails> listOfBookingdetails ; 


   

}
