/*
 * Created on 2023-05-31 ( 14:37:07 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package duan.sportify.entities;

import java.io.Serializable;

import java.util.List;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * JPA entity class for "Sizes"
 *
 * @author Telosys
 *
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name="sizes", catalog="sportify" )
public class Sizes implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="sizeID", nullable=false)
    private Integer    sizeid ;

    //--- ENTITY DATA FIELDS 
    @Column(name="sizeName", nullable=false, length=10)
    private String     sizename ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="sizes")
    private List<Mgrproducts> listOfMgrproducts ; 


    

}
