/*
 * Created on 2023-05-31 ( 14:37:07 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package duan.sportify.entities;

import java.io.Serializable;

import java.util.List;
import jakarta.persistence.*;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * JPA entity class for "Sporttype"
 *
 * @author Telosys
 *
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name="sporttype", catalog="sportify" )
public class Sporttype implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="sportTypeID", nullable=false, length=6)
    private String     sporttypeid ;

    //--- ENTITY DATA FIELDS 
    @Column(name="categoryName", nullable=false, length=30)
    private String     categoryname ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="sporttype")
    private List<Teams> listOfTeams ; 

    @OneToMany(mappedBy="sporttype")
    private List<Fields> listOfFields ; 


    

}
