/*
 * Created on 2023-06-08 ( 15:10:58 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package duan.sportify.entities;

import java.io.Serializable;
import java.util.List;
import jakarta.persistence.*;

/**
 * JPA entity class for "Sporttype"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="sporttype", catalog="sportify" )
public class Sporttype implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="sportTypeID", nullable=false, length=6)
    private String     sporttypeid ;

    //--- ENTITY DATA FIELDS 
    @Column(name="categoryName", nullable=false, length=30)
    private String     categoryname ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="sporttype")
    private List<Teams> listOfTeams ; 

    @OneToMany(mappedBy="sporttype")
    private List<Fields> listOfFields ; 


    /**
     * Constructor
     */
    public Sporttype() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setSporttypeid( String sporttypeid ) {
        this.sporttypeid = sporttypeid ;
    }
    public String getSporttypeid() {
        return this.sporttypeid;
    }

    public void setCategoryname( String categoryname ) {
        this.categoryname = categoryname ;
    }
    public String getCategoryname() {
        return this.categoryname;
    }

    //--- GETTERS FOR LINKS
    public List<Teams> getListOfTeams() {
        return this.listOfTeams;
    } 

    public List<Fields> getListOfFields() {
        return this.listOfFields;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(sporttypeid);
        sb.append("|");
        sb.append(categoryname);
        return sb.toString(); 
    } 

}
