/*
 * Created on 2023-06-14 ( 09:06:03 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package duan.sportify.entities;

import java.io.Serializable;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnore;

import jakarta.persistence.*;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * JPA entity class for "Sporttype"
 *
 * @author Telosys
 *
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name="sporttype", catalog="sportify" )
public class Sporttype implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="sporttypeid", nullable=false, length=6)
    private String     sporttypeid ;

    //--- ENTITY DATA FIELDS 
    @Column(name="categoryname", nullable=false, length=30)
    private String     categoryname ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @JsonIgnore
    @OneToMany(mappedBy="sporttype")
    private List<Field> listOfField ; 
    @JsonIgnore
    @OneToMany(mappedBy="sporttype")
    private List<Teams> listOfTeams ;

    
    

    
}
