/*
 * Created on 2023-06-14 ( 09:06:03 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package duan.sportify.entities;

import java.io.Serializable;
import java.time.LocalDate;

import jakarta.persistence.*;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * JPA entity class for "Teamdetails"
 *
 * @author Telosys
 *
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name="teamdetails", catalog="sportify" )
public class Teamdetails implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="teamdetailid", nullable=false)
    private Integer    teamdetailid ;

    //--- ENTITY DATA FIELDS 
    @Column(name="teamid", nullable=false)
    private Integer    teamid ;

    @Column(name="username", nullable=false, length=16)
    private String     username ;
    
    @Temporal(TemporalType.DATE)
    @Column(name="joindate", nullable=false)
    private LocalDate joindate ;
    
    @Column(name="infouser", length=5000)
    private String     infouser ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="username", referencedColumnName="username", insertable=false, updatable=false)
    private Users      users ; 

    @ManyToOne
    @JoinColumn(name="teamid", referencedColumnName="teamid", insertable=false, updatable=false)
    private Teams      teams ; 


    

}
