/*
 * Created on 2023-06-14 ( 09:06:03 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package duan.sportify.entities;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnore;

import jakarta.persistence.*;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * JPA entity class for "Teams"
 *
 * @author Telosys
 *
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name="teams", catalog="sportify" )
public class Teams implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="teamid", nullable=false)
    private Integer    teamid ;

    //--- ENTITY DATA FIELDS 
    @Column(name="sporttypeid", nullable=false, length=6)
    private String     sporttypeid ;

    @Column(name="nameteam", nullable=false, length=50)
    private String     nameteam ;

    @Column(name="quantity", nullable=false)
    private Integer    quantity ;

    @Column(name="avatar", length=100)
    private String     avatar ;

    @Column(name="contact", nullable=false, length=10)
    private String     contact ;

    @Column(name="descriptions", length=1000)
    private String     descriptions ;

    @Column(name="username", nullable=false, length=16)
    private String     username ;

    @Temporal(TemporalType.DATE)
    @Column(name="createdate", nullable=false)
    private Date       createdate ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="sporttypeid", referencedColumnName="sporttypeid", insertable=false, updatable=false)
    private Sporttype  sporttype ; 

    @ManyToOne
    @JoinColumn(name="username", referencedColumnName="username", insertable=false, updatable=false)
    private Users      users ; 
    @JsonIgnore
    @OneToMany(mappedBy="teams")
    private List<Teamdetails> listOfTeamdetails ; 


   

}
