/*
 * Created on 2023-06-06 ( 15:20:49 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package duan.sportify.entities;

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import jakarta.persistence.*;

/**
 * JPA entity class for "Teams"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="teams", catalog="sportify" )
public class Teams implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="teamID", nullable=false)
    private Integer    teamid ;

    //--- ENTITY DATA FIELDS 
    @Column(name="sportTypeID", nullable=false, length=6)
    private String     sporttypeid ;

    @Column(name="nameTeam", nullable=false, length=50)
    private String     nameteam ;

    @Column(name="quantity", nullable=false)
    private Integer    quantity ;

    @Column(name="avatar", length=100)
    private String     avatar ;

    @Column(name="contact", nullable=false, length=10)
    private String     contact ;

    @Column(name="descriptions", length=1000)
    private String     descriptions ;

    @Column(name="username", nullable=false, length=16)
    private String     username ;

    @Temporal(TemporalType.DATE)
    @Column(name="createDate", nullable=false)
    private Date       createdate ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="teams")
    private List<Teamdetails> listOfTeamdetails ; 

    @ManyToOne
    @JoinColumn(name="username", referencedColumnName="username", insertable=false, updatable=false)
    private Users      users ; 

    @ManyToOne
    @JoinColumn(name="sportTypeID", referencedColumnName="sportTypeID", insertable=false, updatable=false)
    private Sporttype  sporttype ; 


    /**
     * Constructor
     */
    public Teams() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setTeamid( Integer teamid ) {
        this.teamid = teamid ;
    }
    public Integer getTeamid() {
        return this.teamid;
    }

    public void setSporttypeid( String sporttypeid ) {
        this.sporttypeid = sporttypeid ;
    }
    public String getSporttypeid() {
        return this.sporttypeid;
    }

    public void setNameteam( String nameteam ) {
        this.nameteam = nameteam ;
    }
    public String getNameteam() {
        return this.nameteam;
    }

    public void setQuantity( Integer quantity ) {
        this.quantity = quantity ;
    }
    public Integer getQuantity() {
        return this.quantity;
    }

    public void setAvatar( String avatar ) {
        this.avatar = avatar ;
    }
    public String getAvatar() {
        return this.avatar;
    }

    public void setContact( String contact ) {
        this.contact = contact ;
    }
    public String getContact() {
        return this.contact;
    }

    public void setDescriptions( String descriptions ) {
        this.descriptions = descriptions ;
    }
    public String getDescriptions() {
        return this.descriptions;
    }

    public void setUsername( String username ) {
        this.username = username ;
    }
    public String getUsername() {
        return this.username;
    }

    public void setCreatedate( Date createdate ) {
        this.createdate = createdate ;
    }
    public Date getCreatedate() {
        return this.createdate;
    }

    //--- GETTERS FOR LINKS
    public List<Teamdetails> getListOfTeamdetails() {
        return this.listOfTeamdetails;
    } 

    public Users getUsers() {
        return this.users;
    } 

    public Sporttype getSporttype() {
        return this.sporttype;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(teamid);
        sb.append("|");
        sb.append(sporttypeid);
        sb.append("|");
        sb.append(nameteam);
        sb.append("|");
        sb.append(quantity);
        sb.append("|");
        sb.append(avatar);
        sb.append("|");
        sb.append(contact);
        sb.append("|");
        sb.append(descriptions);
        sb.append("|");
        sb.append(username);
        sb.append("|");
        sb.append(createdate);
        return sb.toString(); 
    } 

}
