/*
 * Created on 2023-06-06 ( 15:20:49 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package duan.sportify.entities;

import java.io.Serializable;
import jakarta.persistence.*;

/**
 * JPA entity class for "Teamdetails"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="teamdetails", catalog="sportify" )
public class Teamdetails implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="teamDetailID", nullable=false)
    private Integer    teamdetailid ;

    //--- ENTITY DATA FIELDS 
    @Column(name="teamID", nullable=false)
    private Integer    teamid ;

    @Column(name="username", nullable=false, length=16)
    private String     username ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="teamID", referencedColumnName="teamID", insertable=false, updatable=false)
    private Teams      teams ; 

    @ManyToOne
    @JoinColumn(name="username", referencedColumnName="username", insertable=false, updatable=false)
    private Users      users ; 


    /**
     * Constructor
     */
    public Teamdetails() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setTeamdetailid( Integer teamdetailid ) {
        this.teamdetailid = teamdetailid ;
    }
    public Integer getTeamdetailid() {
        return this.teamdetailid;
    }

    public void setTeamid( Integer teamid ) {
        this.teamid = teamid ;
    }
    public Integer getTeamid() {
        return this.teamid;
    }

    public void setUsername( String username ) {
        this.username = username ;
    }
    public String getUsername() {
        return this.username;
    }

    //--- GETTERS FOR LINKS
    public Teams getTeams() {
        return this.teams;
    } 

    public Users getUsers() {
        return this.users;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(teamdetailid);
        sb.append("|");
        sb.append(teamid);
        sb.append("|");
        sb.append(username);
        return sb.toString(); 
    } 

}
