/*
 * Created on 2023-05-31 ( 14:37:07 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package duan.sportify.entities;

import java.io.Serializable;


import jakarta.persistence.*;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * JPA entity class for "Teamdetails"
 *
 * @author Telosys
 *
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name="teamdetails", catalog="sportify" )
public class Teamdetails implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="teamDetailID", nullable=false)
    private Integer    teamdetailid ;

    //--- ENTITY DATA FIELDS 
    @Column(name="teamID", nullable=false)
    private Integer    teamid ;

    @Column(name="username", nullable=false, length=16)
    private String     username ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="teamID", referencedColumnName="teamID", insertable=false, updatable=false)
    private Teams      teams ; 

    @ManyToOne
    @JoinColumn(name="username", referencedColumnName="username", insertable=false, updatable=false)
    private Users      users ; 


    

}
