/*
 * Created on 2023-06-08 ( 15:10:58 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package duan.sportify.entities;

import java.io.Serializable;
import java.util.List;
import jakarta.persistence.*;

/**
 * JPA entity class for "Users"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="users", catalog="sportify" )
public class Users implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="username", nullable=false, length=16)
    private String     username ;

    //--- ENTITY DATA FIELDS 
    @Column(name="passwords", nullable=false, length=16)
    private String     passwords ;

    @Column(name="firstName", nullable=false, length=50)
    private String     firstname ;

    @Column(name="lastName", nullable=false, length=50)
    private String     lastname ;

    @Column(name="phone", nullable=false, length=10)
    private String     phone ;

    @Column(name="email", nullable=false, length=50)
    private String     email ;

    @Column(name="address", nullable=false, length=100)
    private String     address ;

    @Column(name="image", length=50)
    private String     image ;

    @Column(name="gender", nullable=false)
    private Boolean    gender ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="users")
    private List<Authorized> listOfAuthorized ; 

    @OneToMany(mappedBy="users")
    private List<Bookings> listOfBookings ; 

    @OneToMany(mappedBy="users")
    private List<Teamdetails> listOfTeamdetails ; 

    @OneToMany(mappedBy="users")
    private List<Orders> listOfOrders ; 

    @OneToMany(mappedBy="users")
    private List<Favoritefield> listOfFavoritefield ; 

    @OneToMany(mappedBy="users")
    private List<Teams> listOfTeams ; 


    /**
     * Constructor
     */
    public Users() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setUsername( String username ) {
        this.username = username ;
    }
    public String getUsername() {
        return this.username;
    }

    public void setPasswords( String passwords ) {
        this.passwords = passwords ;
    }
    public String getPasswords() {
        return this.passwords;
    }

    public void setFirstname( String firstname ) {
        this.firstname = firstname ;
    }
    public String getFirstname() {
        return this.firstname;
    }

    public void setLastname( String lastname ) {
        this.lastname = lastname ;
    }
    public String getLastname() {
        return this.lastname;
    }

    public void setPhone( String phone ) {
        this.phone = phone ;
    }
    public String getPhone() {
        return this.phone;
    }

    public void setEmail( String email ) {
        this.email = email ;
    }
    public String getEmail() {
        return this.email;
    }

    public void setAddress( String address ) {
        this.address = address ;
    }
    public String getAddress() {
        return this.address;
    }

    public void setImage( String image ) {
        this.image = image ;
    }
    public String getImage() {
        return this.image;
    }

    public void setGender( Boolean gender ) {
        this.gender = gender ;
    }
    public Boolean getGender() {
        return this.gender;
    }

    //--- GETTERS FOR LINKS
    public List<Authorized> getListOfAuthorized() {
        return this.listOfAuthorized;
    } 

    public List<Bookings> getListOfBookings() {
        return this.listOfBookings;
    } 

    public List<Teamdetails> getListOfTeamdetails() {
        return this.listOfTeamdetails;
    } 

    public List<Orders> getListOfOrders() {
        return this.listOfOrders;
    } 

    public List<Favoritefield> getListOfFavoritefield() {
        return this.listOfFavoritefield;
    } 

    public List<Teams> getListOfTeams() {
        return this.listOfTeams;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(username);
        sb.append("|");
        sb.append(passwords);
        sb.append("|");
        sb.append(firstname);
        sb.append("|");
        sb.append(lastname);
        sb.append("|");
        sb.append(phone);
        sb.append("|");
        sb.append(email);
        sb.append("|");
        sb.append(address);
        sb.append("|");
        sb.append(image);
        sb.append("|");
        sb.append(gender);
        return sb.toString(); 
    } 

}
