/*
 * Created on 2023-05-31 ( 14:37:07 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package duan.sportify.entities;

import java.io.Serializable;
import java.util.Date;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * JPA entity class for "Voucher"
 *
 * @author Telosys
 *
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name="voucher", catalog="sportify" )
public class Voucher implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="voucherID", nullable=false, length=20)
    private String     voucherid ;

    //--- ENTITY DATA FIELDS 
    @Column(name="discountPercent", nullable=false)
    private Integer    discountpercent ;

    @Temporal(TemporalType.DATE)
    @Column(name="startDate", nullable=false)
    private Date       startdate ;

    @Temporal(TemporalType.DATE)
    @Column(name="endDate", nullable=false)
    private Date       enddate ;


    //--- ENTITY LINKS ( RELATIONSHIP )

   

}
